### PR TITLE
Added GetRootFolderId()

### PR DESCRIPTION
**Pull request by jabounet**

### CODE REVIEW

**Comment by rvk01** [comment]
Is rootFolderId needed anywhere? I read that "You can use the alias root to refer to the root folder anywhere a file ID is provided". https://developers.google.com/drive/v3/web/folder

Also on this page: https://developers.google.com/drive/v3/web/migration
rootFolderId	files.get with fileId=root and ?fields=id
So I'm not sure rootFolderId is needed anymore in version 3.

You also retrieved it from the version 2 of the api: /drive/v2/about

**Comment by jabounet** [comment]
I thought it would be useful for listing files into folders since parent id is not 'root'

**Comment by rvk01** [comment]
I was under the impression files without a parentId would be in the "root". But I see now there is a parent. But there is also a "isRoot": true when the file is in the root so using that you already know the rootFolderId because "isRoot": true for those.

**Comment by jabounet** [comment]
You must be right please keep the function it will be useful to know quotas etc... Just few things to rewrite

**Comment by rvk01** [comment]
No problem. Maybe eventually all the v2/ (version 2) of the api needs to be written to v3/ (version 3). But I already saw that version 3 of get.files gives back a lot less information. So that could be a major rewrite. At this point v2 and v3 are mixed in the google_drive.pas. (not sure how long that's possible)

**Comment by jabounet** [comment]
You're right, I saw that for example that the rootfolderid was not present in the v3, maybe then for a good reason (i should have seen isroot boolean in the files :( ).

**Comment by rvk01** [comment]
Of course the GetRootFolderId() could be used as starting point before using populate (or ListFiles) and only retrieve files in that root. When somebody doubleclicks on a directory, only then you could retrieve the files in that directory. That way you wouldn't need to retrieve ALL the files on the drive in an explorer like program.

**Pull request merged**
