### PR TITLE
Delete File (all types, not only revisions)

### PR DESCRIPTION
**Pull request by jabounet**
micro changes... no time unfortunately :(

Do you know if it is possible to easily get parent's parent ? (in order to go back (previous folder) while listing files) ?
Regards

### CODE REVIEW

**Comment by rvk01** [comment]
A file has a parent. So if you want to go back one directory **you need to retrieve that parent and look at the parent of that parent**. Then you can get a list of the grandparents files. I'm not sure if there is another way.

**Comment by jabounet** [comment]
Right, but I can't figure out how to retrieve that, I'll have a look at that. Thanks Rvk!

**Comment by rvk01** [comment]
Wouldn't just getting the meta-data of the parent give you all the info (i.e. the parent of that parent) ?
With GET https://www.googleapis.com/drive/v3/files/fileId with parentId in the fileId field would give you that info I guess (because folder is just the same as a file-resource).
https://developers.google.com/drive/v3/reference/files/get

**Comment by jabounet** [comment]
OK i'll try that

**Comment by jabounet** [comment]
I'll do that, going to change to v3 API too, some things to change, I'm on it, I'll post that tomorrow

**Pull request merged**
