### PR TITLE
Export Google Documents Files : Add popupmenu

### PR DESCRIPTION
**Pull request by jabounet**
It's just a test, may you have a look at this when you have enough time ?
Just select a google document in the list , then right click on it, and select the correct export mimetype, it saves it in the application folder.

### CODE REVIEW

**Comment by rvk01** [comment]
I did merge your pull request "Test (not to merge)". Was/is that a problem?
It was all part of one big pull request with 6 commits so you didn't delete that first commit.

**Comment by jabounet** [comment]
Not at all, I just committed some files that were not working (some procedures were empty), but it should be OK now as the next commits completed the files. If you have time could you just test to see if it works ? I tried something with pop-up menu but I think my code is not very neat..

**Comment by rvk01** [comment]
I don't have time yet. I'll try to make some time the coming days for it.

**Comment by jabounet** [comment]
No problem !! See ya rvk

**Pull request merged**
