### PR TITLE
Weird behavior downloading files / revisions

### PR DESCRIPTION
**Pull request by jabounet**
Could you have a look, it mixes titles / filenames...

### CODE REVIEW

**Comment by rvk01** [comment]
I'm not sure what you mean. I do see title in StringGrid4 is never filled in. Further... on Google drive there is no such thing as Filename. The OriginalFilename for uploading is retained but newly created files on Google Drive don't have a Filename, only a title. When downloading you need to take title as Filename (in case there is no filename).

**Comment by jabounet** [comment]
for revisions, the originalfilename is used, whereas the title is used in files...
With the download modified, it downloads contents from one file but with the wrong name..., just try, it's not clear :)
I hadn't have enough time to look at that, I will do that soon

**Comment by rvk01** [comment]
I get "Retrieving revisions of the current file FileId".
But you have the same StringGrid1DblClick for StringGrid4. That can't be right.
How do you download a revision?
You have a StringGrid4DblClick that does that but you haven't assigned that function to any event.
So **couple** that function with the doubleclick for StringGrid4 and it will be called.

Next is the Filename in that function. If there is no OriginalFilename (which happens a lot for my files) you end up with filename = '' and it will give an error. You need to fill the title of stringgrid4 with the title of the filelist. Google doesn't give back the title for the revision because you need to take the file-title. And if Original filename = '' you need to take title as filename (which I did in StringGrid1DblClick).

**Comment by rvk01** [comment]
So at least do this...

-  couple the correct function for doubleclick
-  pass title to stringgrid4
```
 for Rev := 0 to Length(A) - 1 do
      begin;
        StringGrid4.Cells[1, Rev + 1] := TStringGrid(Sender).cells[1, TStringGrid(Sender).Row];
        StringGrid4.Cells[8, Rev + 1] := A[Rev].revisionid;
```
-  Make StringGrid4DblClick this
```
procedure TMainform.StringGrid4DblClick(Sender: TObject);
var fileid, revisionid, filename: string;
begin
  with TStringGrid(Sender) do
  begin
    filename := cells[4, Row];
    FileId := cells[6, Row];
    revisionid := cells[8, Row];
    if Filename = '' then Filename := cells[1, Row]; // title
  end;
  Jdrive.DownloadFile(fileid, filename, revisionid);
end;
```

**Comment by rvk01** [comment]
O, and next... if the file doesn't have an OriginalFilename and is a real Google Document it needs to be converted first. When trying to download such a revision you get a 403 error and this json:
Error downloading file [403]
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "fileNotDownloadable",
    "message": "Only files with binary content can be downloaded. Use Export with Google Docs files.",
    "locationType": "parameter",
    "location": "alt"
   }
  ],
  "code": 403,
  "message": "Only files with binary content can be downloaded. Use Export with Google Docs files."
 }
}
```

**Comment by jabounet** [comment]
I only uploaded mainfrm.pas, that's why the dblclick function was not assigned I think

**Comment by jabounet** [comment]
have you tried the download revision function (double clicking on a revision ?)
Do you get the correct file ?
:)

**Comment by rvk01** [comment]
I do get the correct file. I even changed something and downloaded the original revision fine. I also uploaded a version with a different filename to that fileid but the routine didn't give that new filename back. I guess only the original filename is used. But as for downloading it worked fine.

**Comment by rvk01** [comment]
I have uploaded a new version. If you have the time you can check out the last tab (Drive-Tab). Click Button1. Double click a file and the revisions will be shown in the lower panel. Double click a revision and it will download. It only works for now for uploaded files. Not yet for real Google Documents. I need to build in the conversion-link. (Sheets need to download as Excel and Docs need to download as Word files). Does downloading a revision in that version work for you (to get the correct file)?

**Comment by rvk01** [comment]
I see now where it goes wrong. Your changes with GetUploadUrl with filename uses filename for description. So when you're going to upload a revision the title/description changes to filename and the originalfilename becomes the old title/description (which is very confusing. When you're going to upload a revision the title should remain the same and the original filename should take the upload-filename.

Normal behavior in Drive is that title is the actual name. When uploading revisions the title stays the same and upload-filename is put in original filename. When downloading, title is always taken with optional extension of original filename. So original filename is not used for anything at all (except extension when downloading a revision). When downloading the current version only the title is used (without any extension unless it is in the title-name).

To make matters worse... The Drive client leaves the extension. Even when renaming the title online without extension. And renaming it in the client puts the extension back in the title (also online). Yeah... neat... :)

**Comment by jabounet** [comment]
Indeed, what a mess :)

**Pull request merged**
