### PR TITLE
Changes to v3

### PR DESCRIPTION
**Pull request by jabounet**
Just an issue with retrieving all files properties

Putting "&Fields=*" into URL parameters only shows the basic properties: id, name, mimetype and kind...

It works with a specific id in the URL :"https//....../files/[...id of file...]&Fields=*" then it shows all properties
But with "https://....../files&Fields=* it won't work.....

I tried to specify fields=* in the google api tester and here, it shows everything... I don't understand why...

Could you just have a look ?

### CODE REVIEW

**Comment by rvk01** [comment]
That's weird. If it works with the "try out" it should work anywhere. I do see an error in your comment. .../files&Fields= isn't a valid url. A normal url needs to be separated from the parameters with ?. And the parameters need to be separated by &. So you should use ? Between /files and Fields. Further more. It is discouraged to use * as Fields. If you know which fields you want you need to set those. Only when you want all fields you can use *.

**Comment by jabounet** [comment]
You're right, sorry I wrote too fast.
the URL actually is "https://....files**?**[...]&Fields=*" as in googldrive.pas
it does the same if I put the formatted URL in google chrome (there only are 4 fields shown)...

**Comment by jabounet** [comment]
The current URL :  
https://www.googleapis.com/drive/v3/files?access_token=[access_token]&maxResults=1000&orderBy=folder,modifiedTime%20desc,name&Fields=*&q="root"%20in%20parents

**Comment by jabounet** [comment]
May you just try with your access token and open it with chrome ?
Do you only see 4 fields (name, id , kind and mimetype or everything ?)

**Comment by jabounet** [comment]
OMG I'm so stupid !!!!
I just failed putting an uppercase in the F of fields !!!!
Too bad, I'm so shameful

**Comment by jabounet** [comment]
it's ok, it works now, sorry rvk !!

**Comment by rvk01** [comment]
aaaarghhh... yeah I figured that out just a minute ago too :D 
Hihih, what a small capital letter can do :)

**Comment by jabounet** [comment]
Sorry for the waste of time :( 
Don't forget I'm a noob :)

**Pull request merged**
