### PR TITLE
TGoogleDriveInformation

### PR DESCRIPTION
**Pull request by jabounet**
for usage, limits, etc...

### CODE REVIEW

**Comment by jabounet** [comment]
Sorry Rvk, I only have very short and fragmented time (because I'm at work), I won't annoy you anymore today :)
Thanks very much !!!

**Comment by rvk01** [comment]
No problem.
B.T.W. Can't you combine the GetRootFolderId() with the new AboutGdrive() function? It calls the same URL (doesn't it) so filling rootFolderID into TGoogleDriveInformation would make sense. Just one call to do to get both values.

**Comment by jabounet** [comment]
Yeah but v3 don't give the rootidfolder

**Comment by rvk01** [comment]
Yeah, I saw that. But v2 also gives usage and max information so you don't even need v3.usage :D And when finally switching all to v3 in the future you don't need the rootfolderid anymore. But until then one call to v2.about would be sufficient and get you all ;)

**Comment by jabounet** [comment]
yeah you're right... as usual :)

**Comment by jabounet** [comment]
BRB

**Comment by jabounet** [comment]
Is it good to use records, or am I completly wrong, should I create an object ?

**Comment by rvk01** [comment]
As I see it there are two ways in google_drive.pas that do the same. .Populate() and ..ListFiles(). Both retrieve files. So eventually only one needs to be used. I used a TMemoryDataset so it acts like a normal TDataset (as in database) but that was just a choice back when I started. Using a record-structure is also fine. Maybe when the records-structure becomes too limited, or you need to do something with it like sorting or something, a TList<record> or other generic could be used. But for now a record-structure is clear and enough. When switching to objects (which is also possible) you could store the original Json of that file in a string and have properties which retrieve the value on command. The objects could be stored in an array or in a TList<object>.

If you add alllllll possible Google-Api-options you end up with something like this:
https://github.com/graemeg/freepascal/blob/master/packages/googleapi/src/googledrive.pp
For me that library was overkill and I wanted something simpler (hence this version).

**Pull request merged**
